# Generated by Django 5.2.7 on 2025-10-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, null=True, verbose_name='عنوان')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='productFeatures',
            field=models.ManyToManyField(related_name='products', to='base.productfeatures'),
        ),
    ]
