# Generated by Django 5.2.7 on 2025-10-09 08:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'شخص', 'verbose_name_plural': 'اشخاص'},
        ),
        migrations.AddField(
            model_name='person',
            name='code',
            field=models.CharField(max_length=13, null=True, verbose_name='کد ملی'),
        ),
        migrations.AddField(
            model_name='person',
            name='phone',
            field=models.CharField(max_length=13, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must contain only digits', regex='^\\d+$')], verbose_name='تلفن'),
        ),
    ]
