# Generated by Django 5.2.7 on 2025-10-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_productfeatures_product_productfeatures'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.IntegerField(blank=True, null=True, verbose_name='تخفیف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('0', 'XXL'), ('1', 'XL'), ('2', 'L'), ('3', 'M')], max_length=1, null=True, verbose_name='سایز'),
        ),
    ]
