# Generated by Django 5.2.7 on 2025-10-02 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_blog_released_at_alter_blog_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='test',
            field=models.CharField(blank=True, default='hello world', max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=models.TextField(blank=True, max_length=2047, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=127, null=True),
        ),
    ]
