# Generated by Django 5.2.7 on 2025-10-02 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_blog_test_alter_blog_body_alter_blog_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=127, null=True)),
                ('last_name', models.CharField(max_length=127, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='blog',
            name='test',
        ),
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.student'),
        ),
    ]
