# Generated by Django 5.2.7 on 2025-10-09 09:04

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_webadmin_writer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webadmin',
            options={'verbose_name': 'منشی', 'verbose_name_plural': 'منشی ها'},
        ),
        migrations.AlterModelOptions(
            name='writer',
            options={'verbose_name': 'نویسنده', 'verbose_name_plural': 'نویسنده ها'},
        ),
        migrations.AddField(
            model_name='person',
            name='birthDate',
            field=django_jalali.db.models.jDateField(null=True),
        ),
    ]
