# Generated by Django 5.2.7 on 2025-10-09 09:08

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_webadmin_options_alter_writer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birthDate',
            field=django_jalali.db.models.jDateTimeField(null=True, verbose_name='تاریخ تولد'),
        ),
    ]
