# Generated by Django 5.2.7 on 2025-10-30 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.product'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='summary',
            field=models.CharField(choices=[('0', 'I suggest this Product'), ('1', "I don't suggest this Product"), ('2', 'I have no idea')], max_length=1, null=True),
        ),
    ]
