# Generated by Django 5.2.7 on 2025-10-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_student_remove_blog_test_blog_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='readers',
            field=models.ManyToManyField(related_name='blogs', to='base.student'),
        ),
    ]
